/**
 * @license
 * Visual Blocks Editor
 *
 * Copyright 2019 Google Inc.
 * https://developers.google.com/blockly/
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * @fileoverview An object that owns a block's rendering SVG elements.
 * @author fenichel@google.com (Rachel Fenichel)
 */

'use strict';

goog.provide('Blockly.geras.PathObject');

goog.require('Blockly.blockRendering.IPathObject');
goog.require('Blockly.utils.dom');


/**
 * An object that handles creating and setting each of the SVG elements
 * used by the renderer.
 * @param {!SVGElement} root The root SVG element.
 * @constructor
 * @implements {Blockly.blockRendering.IPathObject}
 * @package
 */
Blockly.geras.PathObject = function(root, block) {
  this.svgRoot = root;
  this.block_ = block;

  // The order of creation for these next three matters, because that
  // effectively sets their z-indices.

  /**
   * The dark path of the block.
   * @type {SVGElement}
   * @package
   */
  this.svgPathDark = Blockly.utils.dom.createSvgElement('path',
      {'class': 'blocklyPathDark', 'transform': 'translate(1,1)'},
      this.svgRoot);

  /**
   * The primary path of the block.
   * @type {SVGElement}
   * @package
   */
  this.svgPath = Blockly.utils.dom.createSvgElement('path',
      {'class': 'blocklyPath'}, this.svgRoot);

  /**
   * The light path of the block.
   * @type {SVGElement}
   * @package
   */
  this.svgPathLight = Blockly.utils.dom.createSvgElement('path',
      {'class': 'blocklyPathLight'}, this.svgRoot);
};

/**
 * Set each of the paths generated by the renderer onto the respective SVG element.
 * @param {string} mainPath The main path.
 * @param {string} highlightPath The highlight path.
 * @package
 */
Blockly.geras.PathObject.prototype.setPaths = function(mainPath, highlightPath) {
  this.svgPath.setAttribute('d', mainPath);
  this.svgPathDark.setAttribute('d', mainPath);
  this.svgPathLight.setAttribute('d', highlightPath);
};

Blockly.geras.PathObject.prototype.updateStyle = function() {
  var colourPrimary = this.block_.getColourPrimary();
  this.svgPath.setAttribute('fill', colourPrimary);

  this.svgPathLight.setAttribute('display', '');
  this.svgPathDark.setAttribute('display', '');

  var colourLight = Blockly.utils.colour.blend('white', colourPrimary, 0.3);
  var colourDark = Blockly.utils.colour.blend('black', colourPrimary, 0.2);
  this.svgPathLight.setAttribute('stroke', colourLight);
  this.svgPathDark.setAttribute('fill', colourDark);
};

Blockly.geras.PathObject.prototype.updateShadowStyle = function() {
  this.svgPath.setAttribute('fill', this.getColourShadow());
  this.svgPathLight.setAttribute('display', 'none');
  this.svgPathDark.setAttribute('display', 'none');
};

Blockly.geras.PathObject.prototype.getColourShadow = function() {
  var colourSecondary = this.block_.getColourSecondary();
  if (colourSecondary) {
    return colourSecondary;
  }
  return Blockly.utils.colour.blend(
      'white', this.block_.getColourPrimary(), 0.6);
};

/**
 * Flip the SVG paths in RTL.
 * @package
 */
Blockly.geras.PathObject.prototype.flipRTL = function() {
  // Mirror the block's path.
  this.svgPath.setAttribute('transform', 'scale(-1 1)');
  this.svgPathLight.setAttribute('transform', 'scale(-1 1)');
  this.svgPathDark.setAttribute('transform', 'translate(1,1) scale(-1 1)');
};
