primaryBranch: develop
releaseType: node
packageName: blockly
manifest: true
manifestConfig: .github/release-please/config.json
manifestFile: .github/release-please/manifest.json
changelogFile: ./github/CHANGELOG.md
