/**
 * @license
 * Visual Blocks Editor
 *
 * Copyright 2019 Google Inc.
 * https://developers.google.com/blockly/
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * @fileoverview An object that owns a block's rendering SVG elements.
 * @author fenichel@google.com (Rachel Fenichel)
 */

'use strict';

goog.provide('Blockly.console.PathObject');

goog.require('Blockly.utils.dom');


/**
 * An object that handles creating and setting each of the SVG elements
 * used by the renderer.
 * @param {!SVGElement} root The root SVG element.
 * @constructor
 * @implements {Blockly.blockRendering.IPathObject}
 * @package
 */
Blockly.console.PathObject = function(root, block, constants) {
  this.svgRoot = root;
  this.block_ = block;
  this.constants_ = constants;

  /**
   * The primary path of the block.
   * @type {SVGElement}
   * @package
   */
  this.svgPath = Blockly.utils.dom.createSvgElement('path',
      {'class': 'blocklyPath', 'id': 'main'}, this.svgRoot);

  this.topBorder = Blockly.utils.dom.createSvgElement('path',
      {
        'class': 'blocklyPath',
        'id': 'top',
        'stroke-width': this.constants_.TOP_BORDER_WIDTH,
        'fill': 'none'
      }, this.svgRoot);

  this.bottomBorder = Blockly.utils.dom.createSvgElement('path',
      {
        'class': 'blocklyPath',
        'id': 'bot',
        'stroke-width': this.constants_.BOTTOM_BORDER_WIDTH,
        'fill': 'none'
      }, this.svgRoot);
};

/**
 * Set the path generated by the renderer onto the respective SVG element.
 * @param {string} pathString The path.
 * @package
 */
Blockly.console.PathObject.prototype.setPaths =
  function(mainPath, topLeft, bottomRight) {
    this.svgPath.setAttribute('d', mainPath);
    this.topBorder.setAttribute('d', topLeft);
    this.bottomBorder.setAttribute('d', bottomRight);
  };

Blockly.console.PathObject.prototype.updateStyle = function() {
  var colourPrimary = this.block_.getColourPrimary();
  this.svgPath.setAttribute('fill', colourPrimary);

  var border = this.block_.getColourTertiary() ||
      Blockly.utils.colour.blend('white', colourPrimary, 0.3);
  this.topBorder.setAttribute('display', '');
  this.bottomBorder.setAttribute('display', '');
  this.topBorder.setAttribute('stroke', border);
  this.bottomBorder.setAttribute('stroke', border);
};

Blockly.console.PathObject.prototype.updateShadowStyle = function() {
  this.svgPath.setAttribute('fill', this.getColourShadow());
  this.topBorder.setAttribute('display', 'none');
  this.bottomBorder.setAttribute('display', 'none');
};

Blockly.console.PathObject.prototype.getColourShadow = function() {
  var colourSecondary = this.block_.getColourSecondary();
  if (colourSecondary) {
    return colourSecondary;
  }
  return Blockly.utils.colour.blend(
      'white', this.block_.getColourPrimary(), 0.6);
};

/**
 * Flip the SVG paths in RTL.
 * @package
 */
Blockly.console.PathObject.prototype.flipRTL = function() {
  // Mirror the block's path.
  this.svgPath.setAttribute('transform', 'scale(-1 1)');
};
